services:

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tumelosizani
      - MONGO_INITDB_ROOT_PASSWORD=tumelosizani
      - MONGO_INITDB_DATABASE=notificationdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=tumelosizani
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tumelosizani


volumes:
  mongo: