spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: employee-management-service
  datasource:
    url: jdbc:postgresql://localhost:6000/employee-service
