spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: tax-service

  datasource:
    url: jdbc:postgresql://localhost:6000/tax-service

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create